### ISSUE TITLE
Collaborator count shows 2 on private doc

### ISSUE THREAD

**Issue by dfoulser** [salamanders/pledgejs#3]
I just found Pledge, which looks really cool.  I notice that it shows some collaborator count on each bubble.  This really scared me, when I saw that a private doc of mine has 2 collaborators (I was expecting 0).  I ran to check the collaborator list and found it to be private to me.  So the doc is OK with 0 actual collaborators (by my understanding of the English word).  Maybe how you compute the number could take this special case into account?

**Comment by salamanders** [comment]
I've had problems with percent, where it doesn't return email addresses for all of the commenters. So it is possible "you (no email)" counted as 1, and "you (with email)" counted as 2.

**Comment by salamanders** [comment]
Known bug in Google Drive API, can't fix here.  Sorry!

**Comment by netdpb** [comment]
Maybe related: I have a doc where only one other person has made a single edit, and yet I am shown as having contributed only 43%. Others have made comments, but not that many. Can we trust these numbers? How is the contribution # calculated?

**Comment by salamanders** [comment]
Great question! (and pull requests welcome to improve the calculation)

It should be a fast "count how many edits and comments are you" in https://github.com/salamanders/pledgejs/blob/cffe0866149bc6cfcfd65fa2a3ac4d2b89448821/website/js/my_contributions.js#L175

But I noticed that sometimes the email address comes back, and sometimes not.  https://github.com/salamanders/pledgejs/blob/cffe0866149bc6cfcfd65fa2a3ac4d2b89448821/website/js/my_contributions.js#L129-L146
so the totals are... fuzzy.

**Comment by netdpb** [comment]
I think it would help for the tool's documentation to be explicit about what it considers a contribution. I wasn't fully aware that a comment counted the same as an edit.

I also wonder about counting the number of edits. I don't know how large an edit can be in the API. If person A writes an entire document in one sitting, and then person B comes in and adds three commas in different places and corrects the spelling of a word, then did person A contribute only 20%? (That's an extreme example; I imagine "one sitting" is really more than one edit.)

**Comment by netdpb** [comment]
Similarly, if person A leaves three thoughtful comments and person B adds 15 smileys, who does the tool say contributed more?

**Comment by salamanders** [comment]
The smileys of course, they are much more concise.  /s

Having a "number-of-characters-altered" (Levenshtein distance?) would be a much better way to calculate contributions, I'd be all for that!
