### ISSUE TITLE
Allow filtering to a date range

### ISSUE THREAD

**Issue by jyasskin** [salamanders/pledgejs#6]
Especially useful if I'm looking for documents on a project that started in the last year or two.

**Comment by salamanders** [comment]
good FR.  I'm considering a hard 2 year limit because it would be a fast patch.

**Comment by gurayAlsac** [comment]
Are there any limits currently? Or limitations/restrictions on the drive apis that impose an effective limit?

**Comment by salamanders** [comment]
I tossed in a 2 year ago limit.  But no, no API limit that I'm aware of.

```javascript
AND viewedByMeTime>='${oldestDateString}' AND modifiedTime>='${oldestDateString}'
```

**Comment by salamanders** [comment]
Closing because people seem ok with the 2 year range.  Open to a pull request for a more dynamic solution.
